### ISSUE TITLE
OwnCloud 8 compatability

### ISSUE THREAD

**Issue by jdredmond** [simeonackermann/OC-User-Conversations#34]
Conversations page does not load with OwnCloud version 8 installed. The OwnCloud Files page displays when clicking on the Conversations icon. The app was installed as per the instructions, in the correct directory. Permissions are set correctly. I have other apps installed and working.

**Comment by jon-tlmi** [comment]
I also have this issue

**Comment by simeonackermann** [comment]
Adding OC > 8 compatibility with latest commits. 

I will do some more functionality test next days and didn't checked out older OC Versions.
