### ISSUE TITLE
Error on activation: no app name specified

### ISSUE THREAD

**Issue by johappel** [simeonackermann/OC-User-Conversations#36]
"No app name specified"
Try to enable OC-User-Conversations on OC 8.0.2 throw an Error: "No app name specified." Also no App Icon is visible. See screencast: http://gyazo.com/549c2167b7e8822678c398a4dd06ddd7

**Comment by simeonackermann** [comment]
Please check if the name of this app in .../apps/ is just "conversations".

**Comment by simeonackermann** [comment]
Added also an icon now ;)

**Comment by johappel** [comment]
Thank you! That works for me. You mdae me happy :-)))

**Comment by simeonackermann** [comment]
You are welcome! :)
