### ISSUE TITLE
Issue with larger attachments for not admin users

### ISSUE THREAD

**Issue by simeonackermann** [simeonackermann/OC-User-Conversations#38]
Spinning wheel after submit messages with bigger attachments (e.g. 2MB) for not admin users.

**Comment by simeonackermann** [comment]
This bug was based on reports off different users.

But I couldn't  recreate this issues with current OC 8...

**Comment by stonerl** [comment]
I do have a similar problem. Conversation just spins and does not load. I have to clear the browser cache and reload the page to use owncloud again, but as soon as I start conversation I get an endless spinning wheel.

**Comment by stonerl** [comment]
Some additional information. I attached a 46kb PDF. Me and the other users have non-admin-accounts. I had to delete the message in the database to get conversations working again.

**Comment by stonerl** [comment]
OK the problem appears when a file from a subfolder gets shared.

e.g.
"owcloudroot\FILE_A" is ok but
"owncloudroot\subfolder\FILE_B" results in an endless spinning wheel

**Comment by stonerl** [comment]
I dove in the database and found the problem:
```mysql
{"type":"internal_file","fileid":165217,"path":"files%2FNew+text+file.txt","owner":"zxmrs02"}
```
I changed it to this and now it works
```mysql
{"type":"internal_file","fileid":165217,"path":"files%2FSubfolder/New+text+file.txt","owner":"me"}
```

**Comment by stonerl** [comment]
with the latest master I don't have this problem anymore.

**Comment by stonerl** [comment]
Just an update. This only happens when you add a file from a folder that is shared with you by another user.

e.g. User A shared the Folder 1 with me. Inside this Folder is a file called test.txt.
When I add the file to a conversation with User B, the correct path should be 

"Folder+1%2Ftest.txt"

but in the database the entry is just "test.txt"
