### ISSUE TITLE
Attachments not working correctly in 9.0

### ISSUE THREAD

**Issue by SlawaGurevich** [simeonackermann/OC-User-Conversations#48]
The attachments are currently not working correctly, as far as I can see. I can attach image files, however  anything else isn't possible. When I try attaching PDF or other documents, the message textbox turns blank and I can't send the message.

Currently running 0.2.3 on OC9.0

_Selecting the example PDF_
![screen shot 2016-03-26 at 01 45 33](https://cloud.githubusercontent.com/assets/13917864/14057015/7b89afb8-f2f4-11e5-8b76-2fff45b641ce.png)

_Message field turning white_
![screen shot 2016-03-26 at 01 45 39](https://cloud.githubusercontent.com/assets/13917864/14057016/7b8ca664-f2f4-11e5-95e0-06fd4d999889.png)

**Comment by simeonackermann** [comment]
Thanks for the issue, i'll have a look next days.

**Comment by simeonackermann** [comment]
Please try again, it should work now.
